FROM node:20 as build
WORKDIR /frontend
COPY package.json package-lock.json angular.json ./
RUN npm install -g @angular/cli
RUN npm install
COPY . .
RUN ng build --configuration=production
FROM nginx:1.25.3-alpine-slim
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /frontend/dist/crud-teste /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]